import React from 'react'

const page = () => {
    return (
        <div>
            <h1>this is contact page</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium vero non similique quam tenetur dolorem, modi dolore harum placeat ea quaerat recusandae, deserunt necessitatibus impedit pariatur aspernatur reprehenderit sapiente excepturi optio, saepe nulla totam reiciendis. Veniam voluptates sunt ex facere aperiam deserunt ipsum provident ab iste ullam corrupti, ipsam magni? Esse aut distinctio nam id ullam vel hic molestias deserunt blanditiis unde asperiores modi recusandae est totam quasi quidem quia, doloribus perferendis, ea, tempora earum sint amet ipsa? Error sunt mollitia neque sequi repellat expedita numquam doloremque ab asperiores dignissimos. Officiis facilis atque officia perspiciatis vero eaque expedita amet, beatae animi, tempora impedit autem sint numquam ipsum consequatur? Iste, rerum eaque expedita quisquam quod magnam eius magni velit fugiat tenetur impedit modi et ea mollitia molestias laboriosam consequuntur alias quos officia dignissimos temporibus ipsam. Totam, praesentium deserunt! Nobis amet, iure sed, eligendi placeat blanditiis impedit ex molestias expedita quod beatae repellat maxime. Sed modi magnam optio quidem qui distinctio quisquam nesciunt natus debitis, sint magni dolorum reiciendis cumque impedit commodi dolore expedita veniam est. Atque distinctio, ipsa deleniti sint soluta facere, nemo suscipit cumque autem aut eum ab vero odio voluptatibus modi mollitia consequuntur? Fuga, natus tempore iusto ab cupiditate libero ipsam consectetur consequatur deleniti, dolorem nulla sequi laborum corporis, labore facere fugiat! Incidunt ducimus maxime id? Nemo eligendi ipsa porro. Voluptatem, velit voluptas? Magni voluptatibus itaque tenetur maxime quidem harum atque eaque rem esse voluptatum blanditiis unde laborum fugit odio quasi repellendus, minus est culpa iusto veniam? Minima laborum error, ipsam nam quasi sed recusandae eligendi voluptatem hic accusamus provident. Provident excepturi ipsum consectetur, magni nemo iure cum odit mollitia earum error minima laudantium animi illum, sint consequuntur repudiandae quo praesentium possimus? A, nobis facere at suscipit quasi iusto culpa excepturi nihil rem minus corporis minima vel quis autem aliquam soluta possimus beatae commodi nisi blanditiis? Maiores placeat natus itaque aut optio quisquam repellendus dolore quibusdam, cumque repudiandae neque officia. Iste velit veniam dicta obcaecati enim rem neque quisquam accusamus. Dolorum, aperiam consectetur quisquam doloremque numquam libero deserunt quod optio a repudiandae inventore facilis molestias temporibus tenetur nulla beatae repellendus! Hic, cupiditate illo. Eos, quo accusamus? Veritatis iusto magnam dolor impedit animi nostrum, optio, rerum voluptas ad dolorum nulla veniam laboriosam, tempore qui. Consequatur ratione nemo, quo assumenda ad magnam iure corporis nobis facere minima? Velit impedit omnis accusamus distinctio vero dolore, vitae ullam quibusdam minima dolorem doloribus non.</p>
        </div>
    )
}

export default page
